# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2020-02-03 20:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='parametroslibro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcionp', models.CharField(blank=True, max_length=100, null=True)),
                ('valorp', models.IntegerField(blank=True, null=True)),
                ('estadop', models.CharField(blank=True, choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], max_length=30, null=True)),
                ('tipop', models.CharField(blank=True, choices=[('Autor', 'Autor'), ('Capitulo', 'Capitulo')], max_length=50, null=True)),
            ],
        ),
    ]
