# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-09-09 05:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Libro', '0003_auto_20180909_0027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libro',
            name='LMresumen',
        ),
        migrations.RemoveField(
            model_name='libro',
            name='LMtitulo',
        ),
    ]
