# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-11-06 08:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Libro', '0005_auto_20180909_0034'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='libro',
            options={'ordering': ('fechaPublicacion',), 'permissions': (('ver_libro', 'ver libro'),)},
        ),
        migrations.AddField(
            model_name='libro',
            name='fechaPublicacion',
            field=models.DateField(blank=True, null=True),
        ),
    ]
