# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-02-02 01:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Libro', '0007_auto_20190201_1945'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libro',
            name='comentarioSecretaria',
        ),
        migrations.RemoveField(
            model_name='libro',
            name='editableTrueFalse',
        ),
    ]
