# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-02-02 01:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Libro', '0008_auto_20190201_2028'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='comentarioSecretaria',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='libro',
            name='editableTrueFalse',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
