# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2020-02-04 21:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Libro', '0013_auto_20190218_0456'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='tipoEditorial',
            field=models.CharField(blank=True, choices=[('0', 'Editorial Internacional'), ('1', 'Universidad Internacional'), ('2', 'Universidad Tècnica de Cotopaxi'), ('3', 'Universidad Nacional')], max_length=200, null=True),
        ),
    ]
