# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2020-02-04 23:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Libro', '0014_libro_tipoeditorial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='tipoEditorial',
            field=models.CharField(blank=True, choices=[('Editorial Internacional', 'Editorial Internacional'), ('Universidad Internacional', 'Universidad Internacional'), ('Universidad Tècnica de Cotopaxi', 'Universidad Tècnica de Cotopaxi'), ('Universidad Nacional', 'Universidad Nacional')], max_length=200, null=True),
        ),
    ]
