# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2020-02-04 02:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('incentivo', '0001_initial'),
        ('Investigador', '0003_investigador_eventoinv'),
    ]

    operations = [
        migrations.CreateModel(
            name='postulacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(blank=True, choices=[('2', 'Rechazado'), ('1', 'Aceptado'), ('0', 'Pendiente')], max_length=150, null=True)),
                ('incentivo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='incentivo.incentivo')),
                ('investigador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Investigador.Investigador')),
            ],
        ),
    ]
