from django import forms
from apps.Articulos_Cientificos.models import articulos_cientificos


class articuloform(forms.ModelForm):
    class Meta:
        model = articulos_cientificos
        fields = [
            'titulo',
            'estado',
            'iSSN',
            'url',
            'doi',
            'fechaPublicacion',
            'pais',
            'ciudad',
            'baseDatos',
            'revista',
            'volumen',
            'numero',
            'lineaInves',
            'SubLinea',
            'resumen',
            'documento',
            'tipoArticulo',
            'aprobado',
            'palabraClave',
            'estPub',
            'detallado',
            'amplio',
            'especifico',
            'university',
            'idioma',
            'editableTrueFalse',
            'comentarioSecretaria',
            'filialUtc',

        ]
        labels = {
            'titulo': 'Título del Artículo',
            'estado': 'Estado',
            'iSSN': 'ISSN',
            'url': 'Url dónde se encuentra el artículo',
            'doi': 'DOI dónde se encuentra el artículo',
            'fechaPublicacion': 'Fecha de publicación del artículo',
            'pais': 'País dónde se público el artículo',
            'ciudad': 'Ciudad dónde se público el artículo',
            'baseDatos': 'Base de Datos dónde esta indexada la Revista',
            'revista': 'Revista del artículo',
            'volumen': 'Volumen de la Revista',
            'numero': 'Número de la Revista',
            'lineaInves': 'Linea de investigación',
            'SubLinea': 'SubLinea de investigación',
            'resumen': 'Resumen',
            'documento': 'Adjuntar Archivo',
            'tipoArticulo': 'Tipo de artículo',
            'university': 'Institución responsable de la investigación',
            'palabraClave': '',
            'detallado':'Campo detallado',
            'comentarioSecretaria':'Comentario',
            'filialUtc':'Filial UTC (El Artículo es filial de la Universidad Técnica de Cotopaxi)',

        }
        widgets = {
            'titulo': forms.TextInput(attrs={'class': 'form-control', 'required': True, }),
            'estado': forms.Select(attrs={'class': 'form-control', 'required': True}),
            'iSSN': forms.TextInput(attrs={'class': 'form-control', 'required': True}),
            'url': forms.URLInput(attrs={'class': 'form-control', 'required': True}),
            'doi': forms.URLInput(attrs={'class': 'form-control', 'required': False}),
            'fechaPublicacion': forms.TextInput(attrs={'class': 'form-control datepicker', 'type': 'date', 'required': True}),
            'pais': forms.Select(attrs={'class': 'form-control', 'id': 'pais', 'required': False}),
            'ciudad': forms.Select(attrs={'class': 'form-control', 'id': 'ciudad', 'required': False}),
            'baseDatos': forms.CheckboxSelectMultiple(),
            'amplio': forms.Select(attrs={'class': 'form-control', 'id': 'amplio', 'required': True}),
            'especifico': forms.Select(attrs={'class': 'form-control', 'id': 'especifico', 'required': True}),
            'university': forms.Select(attrs={'class': 'form-control', 'id': 'university', 'required': True}),
            'revista': forms.Select(attrs={'class': 'form-control', 'id': 'revista', 'required': True}),
            'volumen': forms.TextInput(attrs={'class': 'form-control', 'required': False}),
            'numero': forms.TextInput(attrs={'class': 'form-control', 'required': False}),
            'lineaInves': forms.Select(attrs={'class': 'form-control', 'id': 'lineaInves', 'required': False}),
            'SubLinea': forms.Select(attrs={'class': 'form-control', 'id': 'SubLinea', 'required': False}),
            'resumen': forms.Textarea(attrs={'class': 'form-control', 'required': True}),
            'documento': forms.FileInput(attrs={'class': 'form-control','id': 'id_documento', 'onchange':'check_file(this)','required': False}),
            'tipoArticulo': forms.Select(attrs={'class': 'form-control', 'required': True}),
            'aprobado': forms.TextInput(attrs={'class': 'form-control', 'required': False}),
            'palabraClave': forms.CheckboxSelectMultiple(),
            'estPub': forms.CheckboxInput(attrs={'class': 'form-control', 'required': False, 'checked': True, 'style': 'display:none'}),
            'detallado': forms.Select(attrs={'class': 'form-control', 'id': 'detallado'}),
            'comentarioSecretaria': forms.Textarea(attrs={'class': 'form-control', 'required': False}),
            'filialUtc': forms.Select(attrs={'class': 'form-control', 'required': True}),

        }

class articuloformdisabled(forms.ModelForm):
    class Meta:
        model = articulos_cientificos
        fields = [
            'titulo',
            'estado',
            'iSSN',
            'url',
            'doi',
            'fechaPublicacion',
            'pais',
            'ciudad',
            'baseDatos',
            'revista',
            'volumen',
            'numero',
            'lineaInves',
            'SubLinea',
            'resumen',
            'documento',
            'tipoArticulo',
            'aprobado',
            'palabraClave',
            'estPub',
            'detallado',
            'amplio',
            'especifico',
            'university',
            'idioma',
            'editableTrueFalse',
            'comentarioSecretaria',
            'filialUtc',

        ]
        labels = {
            'titulo': 'Título del Artículo',
            'estado': 'Estado',
            'iSSN': 'ISSN',
            'url': 'Url dónde se encuentra el artículo',
            'doi': 'DOI dónde se encuentra el artículo',
            'fechaPublicacion': 'Fecha de publicación del artículo',
            'pais': 'País dónde se público el artículo',
            'ciudad': 'Ciudad dónde se público el artículo',
            'baseDatos': 'Base de Datos dónde esta indexada la Revista',
            'revista': 'Revista del artículo',
            'volumen': 'Volumen de la Revista',
            'numero': 'Número de la Revista',
            'lineaInves': 'Linea de investigación',
            'SubLinea': 'SubLinea de investigación',
            'resumen': 'Resumen',
            'documento': 'Adjuntar Archivo',
            'tipoArticulo': 'Tipo de artículo',
            'university': 'Institución responsable de la investigación',
            'palabraClave': '',
            'detallado':'Campo detallado',
            'comentarioSecretaria':'Comentario',
            'filialUtc':'Filial UTC (El Artículo es filial de la Universidad Técnica de Cotopaxi)',

        }
        widgets = {
            'titulo': forms.TextInput(attrs={'class': 'form-control' , 'readonly':'' , 'required': False, }),
            'estado': forms.TextInput(attrs={'class': 'form-control', 'readonly':'', 'required': False}),
            'iSSN': forms.TextInput(attrs={'class': 'form-control', 'readonly':'', 'required': False}),
            'url': forms.TextInput(attrs={'class': 'form-control', 'readonly':'', 'required': False}),
            'doi': forms.TextInput(attrs={'class': 'form-control', 'readonly':'', 'required': False}),
            'fechaPublicacion': forms.TextInput(attrs={'class': 'form-control' , 'readonly':'' , 'required': False, }),
            'pais': forms.TextInput(attrs={'class': 'form-control' , 'readonly':'' , 'required': True, }),
            'ciudad': forms.TextInput(attrs={'class': 'form-control' , 'readonly':'' , 'required': False, }),
            'baseDatos': forms.TextInput(attrs={'class': 'form-control' , 'readonly':'' , 'required': False, }),
            'amplio': forms.TextInput(attrs={'class': 'form-control' , 'readonly':'' , 'required': False, }),
            'especifico': forms.TextInput(attrs={'class': 'form-control' , 'readonly':'' , 'required': False, }),
            'university': forms.TextInput(attrs={'class': 'form-control' , 'readonly':'' , 'required': False, }),
            'revista': forms.TextInput(attrs={'class': 'form-control' , 'id':'revista' , 'readonly':'' , 'required': False, }),
            'volumen': forms.TextInput(attrs={'class': 'form-control', 'readonly':'', 'required': False}),
            'numero': forms.TextInput(attrs={'class': 'form-control', 'readonly':'', 'required': False}),
            'lineaInves': forms.TextInput(attrs={'class': 'form-control' , 'id':'lineaInves'}),
            'SubLinea': forms.TextInput(attrs={'class': 'form-control' , 'id':'SubLinea' , 'required': False, }),
            'resumen': forms.TextInput(attrs={'class': 'form-control', 'readonly':'', 'required': False}),
            'documento': forms.FileInput(attrs={'class': 'form-control', 'required': False}),
            'tipoArticulo': forms.TextInput(attrs={'class': 'form-control', 'readonly':'', 'required': False}),
            'aprobado': forms.TextInput(attrs={'class': 'form-control', 'readonly':'', 'required': False}),
            'palabraClave': forms.TextInput(attrs={'class': 'form-control' , 'readonly':'' , 'required': False, }),
            'estPub': forms.TextInput(attrs={'class': 'form-control' , 'readonly':'' , 'required': False, }),
            'detallado': forms.TextInput(attrs={'class': 'form-control' , 'readonly':'' , 'required': False, }),
            'comentarioSecretaria': forms.Textarea(attrs={'class': 'form-control', 'readonly':'' ,'required': False}),
            'filialUtc': forms.Select(attrs={'class': 'form-control', 'readonly':'', 'required': True}),

        }
