# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-07-08 23:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informacionLaboral', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='informacionlaboral',
            name='ingreso',
            field=models.DateField(blank=True, null=True),
        ),
    ]
