# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-10-01 09:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0001_initial'),
        ('informacionLaboral', '0002_informacionlaboral_ingreso'),
    ]

    operations = [
        migrations.AddField(
            model_name='informacionlaboral',
            name='campus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='campus.campus'),
        ),
    ]
