# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-09-09 05:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Formacion_Academica', '0002_auto_20180909_0029'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formacion_academica',
            name='FAMdescripcion',
        ),
        migrations.RemoveField(
            model_name='formacion_academica',
            name='FAMtipoTitulo',
        ),
        migrations.RemoveField(
            model_name='formacion_academica',
            name='FAMtitulo',
        ),
    ]
