# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-07-06 18:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Investigador', '0002_auto_20180703_1627'),
        ('Sub_Lin_Investigacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='similitud_autores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coordenadax', models.IntegerField()),
                ('coordenaday', models.IntegerField()),
                ('area', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Sub_Lin_Investigacion.sub_lin_investigacion')),
                ('investigator', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Investigador.Investigador')),
            ],
        ),
    ]
