# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-07-03 21:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('palabraClave', '0001_initial'),
        ('universidad', '0001_initial'),
        ('Sub_Lin_Investigacion', '0001_initial'),
        ('Linea_Investigacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='proyecto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=500, null=True)),
                ('montoFinanciado', models.CharField(blank=True, max_length=500, null=True)),
                ('montorecibido', models.CharField(blank=True, max_length=500, null=True)),
                ('fechaInicial', models.DateField()),
                ('fechaFinal', models.DateField()),
                ('estado', models.CharField(blank=True, choices=[('En espera de Presupuesto', 'En espera de Presupuesto'), ('En Ejecución', 'En Ejecución'), ('Finalizado', 'Finalizado')], max_length=500, null=True)),
                ('resumen', models.TextField(blank=True, null=True)),
                ('tipoProyecto', models.CharField(blank=True, choices=[('Formativo', 'Formativo'), ('Generativo', 'Generativo')], max_length=500, null=True)),
                ('documentos', models.FileField(blank=True, null=True, upload_to='proyecto/')),
                ('financiamiento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='universidad.universidad')),
                ('lineaInvestigacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Linea_Investigacion.linea_investigacion')),
                ('palabrasClaves', models.ManyToManyField(blank=True, to='palabraClave.palabraClave')),
                ('subLinea', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Sub_Lin_Investigacion.sub_lin_investigacion')),
            ],
            options={
                'permissions': (('ver_Proyectos', 'ver Proyectos'),),
            },
        ),
    ]
