# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-07-03 21:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('informacionLaboral', '0001_initial'),
        ('pais', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Investigador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(blank=True, max_length=20, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='foto/')),
                ('direccion', models.CharField(blank=True, max_length=500, null=True)),
                ('edad', models.DateField(blank=True, null=True)),
                ('coordenadas', models.CharField(blank=True, max_length=500, null=True)),
                ('telefono', models.CharField(blank=True, max_length=100, null=True)),
                ('genero', models.CharField(blank=True, choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino')], max_length=100, null=True)),
                ('cambio', models.BooleanField()),
                ('documento', models.FileField(blank=True, null=True, upload_to='docSen/')),
                ('informacionLaboral', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='informacionLaboral.informacionLaboral')),
                ('nacionalidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pais.pais')),
            ],
            options={
                'permissions': (('ver_perfil', 'ver perfil'),),
            },
        ),
    ]
