# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2020-02-04 02:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evento', '0001_initial'),
        ('Investigador', '0002_auto_20180703_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='investigador',
            name='eventoInv',
            field=models.ManyToManyField(blank=True, to='evento.evento'),
        ),
    ]
