# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2020-01-30 23:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='parametrosArticulo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(blank=True, max_length=100, null=True)),
                ('valor', models.IntegerField(blank=True, null=True)),
                ('estado', models.CharField(blank=True, choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], max_length=30, null=True)),
                ('tipoIntReg', models.CharField(blank=True, choices=[('Internacional', 'Internacional'), ('Regional', 'Regional')], max_length=50, null=True)),
            ],
        ),
    ]
