# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2020-02-04 02:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='evento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=150, null=True)),
                ('fechaInicio', models.DateField(blank=True, null=True)),
                ('fechaFinal', models.DateField(blank=True, null=True)),
                ('numeroPublicaciones', models.IntegerField(blank=True, null=True)),
                ('estado', models.CharField(blank=True, choices=[('1', 'Activo'), ('0', 'Inactivo')], max_length=150, null=True)),
            ],
        ),
    ]
