# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-11-13 21:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SisRec', '0002_solicitudcolaboracion_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacion',
            name='basedatos',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Articulos_Cientificos.articulos_cientificos'),
        ),
    ]
