# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-11-27 19:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SisRec', '0006_publicacion_proyectosmacro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyectosmacro',
            name='carrera',
        ),
        migrations.RemoveField(
            model_name='publicacion',
            name='proyectosMacro',
        ),
        migrations.DeleteModel(
            name='ProyectosMacro',
        ),
    ]
