# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-11-29 01:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carrera', '0002_auto_20181001_0436'),
        ('SisRec', '0007_auto_20191127_1453'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProyectosMacro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('tipo', models.CharField(max_length=15)),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carrera.carrera')),
            ],
        ),
        migrations.RemoveField(
            model_name='publicacion',
            name='texto',
        ),
        migrations.AddField(
            model_name='publicacion',
            name='proyectosMacro',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='SisRec.ProyectosMacro'),
            preserve_default=False,
        ),
    ]
