# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-12-06 01:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Investigador', '0002_auto_20180703_1627'),
        ('SisRec', '0009_auto_20191128_2331'),
    ]

    operations = [
        migrations.CreateModel(
            name='Likes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like', models.BooleanField()),
                ('investigador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Investigador.Investigador')),
                ('publicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SisRec.Publicacion')),
            ],
        ),
    ]
