# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-12-09 18:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SisRec', '0010_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estadisticas',
            name='disLike',
        ),
        migrations.RemoveField(
            model_name='estadisticas',
            name='like',
        ),
    ]
