# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-12-16 17:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Investigador', '0002_auto_20180703_1627'),
        ('SisRec', '0012_globalkeywordsinvestigador_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='notificacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='DestinoNotificacion', to='Investigador.Investigador')),
                ('origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='OrigenNotificacion', to='Investigador.Investigador')),
                ('publicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SisRec.Publicacion')),
            ],
        ),
    ]
