# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-12-16 18:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SisRec', '0013_notificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacion',
            name='estado',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
