# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-12-24 19:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SisRec', '0014_notificacion_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalkeywords',
            name='termino',
            field=models.CharField(max_length=80),
        ),
    ]
