# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2020-01-21 01:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SisRec', '0015_auto_20191224_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacion',
            name='tema',
            field=models.CharField(max_length=255),
        ),
    ]
