# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-02-18 09:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Sub_Lin_Investigacion', '0002_auto_20181106_0322'),
    ]

    operations = [
        migrations.CreateModel(
            name='textmining',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.IntegerField(blank=True, null=True)),
                ('texto', models.TextField(blank=True, null=True)),
                ('textoAtributo', models.TextField(blank=True, null=True)),
                ('status', models.BooleanField(default=False)),
                ('statusClasificacion', models.BooleanField(default=False)),
                ('sublineaClasificacion', models.ForeignKey(blank=True, max_length=150, null=True, on_delete=django.db.models.deletion.CASCADE, to='Sub_Lin_Investigacion.sub_lin_investigacion')),
            ],
            options={
                'db_table': 'TextMining',
            },
        ),
    ]
