# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-07-03 21:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='capacitacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('areaConocimiento', models.CharField(blank=True, max_length=500, null=True)),
                ('horas', models.IntegerField()),
                ('institucion', models.CharField(blank=True, max_length=500, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=500, null=True)),
                ('evidencias', models.FileField(blank=True, null=True, upload_to='capacitaciones/')),
                ('tipoCapacitacion', models.CharField(blank=True, choices=[('Capacitación pedagógica', 'Capacitación pedagógica'), ('Capacitación técnica', 'Capacitación técnica')], max_length=500, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': (('ver_capacitacion', 'ver capacitación'),),
            },
        ),
    ]
