# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-11-08 01:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SisRec', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudcolaboracion',
            name='estado',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
