# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-11-13 21:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Articulos_Cientificos', '0025_auto_20190218_0456'),
        ('Libro', '0013_auto_20190218_0456'),
        ('Ponencia', '0017_auto_20190409_1722'),
        ('SisRec', '0003_auto_20191113_1636'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicacion',
            name='basedatos',
        ),
        migrations.AddField(
            model_name='publicacion',
            name='articulo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Articulos_Cientificos.articulos_cientificos'),
        ),
        migrations.AddField(
            model_name='publicacion',
            name='libro',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Libro.libro'),
        ),
        migrations.AddField(
            model_name='publicacion',
            name='ponencia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Ponencia.ponencia'),
        ),
    ]
