# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-11-27 19:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SisRec', '0005_proyectosmacro'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacion',
            name='proyectosMacro',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='SisRec.ProyectosMacro'),
            preserve_default=False,
        ),
    ]
