# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-11-29 04:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SisRec', '0008_auto_20191128_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacion',
            name='investigador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Investigador.Investigador'),
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='proyectosMacro',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='SisRec.ProyectosMacro'),
        ),
    ]
