# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-07-03 21:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campoEspecifico', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='campoDetallado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(blank=True, max_length=250, null=True)),
                ('especifico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='campoEspecifico.campoEspecifico')),
            ],
        ),
    ]
