# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-07-06 01:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Ponencia', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ponencia',
            name='autores',
        ),
        migrations.AlterField(
            model_name='ponencia',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
