# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-09-09 04:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ponencia', '0004_remove_ponencia_uploaded_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='ponencia',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, default=1),
            preserve_default=False,
        ),
    ]
