# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-09-09 05:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ponencia', '0008_auto_20180909_0025'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ponencia',
            name='PMnombre',
        ),
        migrations.RemoveField(
            model_name='ponencia',
            name='PMresumen',
        ),
        migrations.RemoveField(
            model_name='ponencia',
            name='PMtitulo',
        ),
    ]
