# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-09-09 05:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ponencia', '0009_auto_20180909_0026'),
    ]

    operations = [
        migrations.AddField(
            model_name='ponencia',
            name='PMnombre',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='ponencia',
            name='PMresumen',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ponencia',
            name='PMtitulo',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
