# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-02-12 02:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ponencia', '0014_remove_ponencia_filialutc'),
    ]

    operations = [
        migrations.AddField(
            model_name='ponencia',
            name='filialUtc',
            field=models.CharField(blank=True, choices=[('Si', 'Si'), ('No', 'No')], max_length=20, null=True),
        ),
    ]
