# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-04-09 22:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pais', '0002_auto_20180807_0448'),
        ('ciudad', '0002_auto_20181106_0322'),
        ('Ponencia', '0016_auto_20190218_0456'),
    ]

    operations = [
        migrations.AddField(
            model_name='ponencia',
            name='ciudad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ciudad.ciudad'),
        ),
        migrations.AddField(
            model_name='ponencia',
            name='pais',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pais.pais'),
        ),
    ]
