# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-07-03 21:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('baseDatos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='revista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=500, unique=True)),
                ('ISSN', models.CharField(blank=True, max_length=250, null=True)),
                ('Cuartil_Pertenece', models.CharField(blank=True, max_length=500, null=True)),
                ('Factor_Impacto', models.CharField(blank=True, max_length=500, null=True)),
                ('Url', models.URLField(blank=True, null=True)),
                ('validar', models.CharField(blank=True, choices=[('Ingresada', 'Ingresada'), ('A revisar', 'A revisar'), ('Corregida', 'Corregida'), ('validada', 'validada')], max_length=500, null=True)),
                ('base', models.ManyToManyField(blank=True, to='baseDatos.baseDatos')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': (('ver_Revista', 'ver Revista'),),
            },
        ),
    ]
