# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-05-28 05:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Revista', '0003_auto_20190214_2131'),
    ]

    operations = [
        migrations.AddField(
            model_name='revista',
            name='cuartil_revista',
            field=models.CharField(blank=True, choices=[('Q1', 'Q1'), ('Q2', 'Q2'), ('Q3', 'Q3'), ('Q4', 'Q4')], max_length=50, null=True),
        ),
    ]
