# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-07-31 22:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Libro', '0013_auto_20190218_0456'),
        ('Investigador', '0002_auto_20180703_1627'),
        ('Articulos_Cientificos', '0025_auto_20190218_0456'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Ponencia', '0017_auto_20190409_1722'),
    ]

    operations = [
        migrations.CreateModel(
            name='certificacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asunto', models.CharField(blank=True, default='Necesito un certificado', max_length=350, null=True)),
                ('fecha_envio', models.DateField(auto_now_add=True, null=True)),
                ('hora_envio', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('estado', models.CharField(blank=True, default='Enviado', max_length=50, null=True)),
                ('nota', models.CharField(blank=True, default='En espera', max_length=350, null=True)),
                ('validar', models.CharField(blank=True, choices=[('Aprobado', 'Aprobado'), ('Denegado', 'Denegado')], default='', max_length=50, null=True)),
                ('notificacion', models.CharField(blank=True, default='0', max_length=50, null=True)),
                ('fecha_actualizacion', models.DateField(auto_now=True, null=True)),
                ('hora_actualizacion', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('articulos_varios', models.ManyToManyField(blank=True, null=True, to='Articulos_Cientificos.articulos_cientificos')),
                ('investigador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Investigador.Investigador')),
                ('libros_varios', models.ManyToManyField(blank=True, null=True, to='Libro.libro')),
                ('ponencias_varios', models.ManyToManyField(blank=True, null=True, to='Ponencia.ponencia')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': (('ver_certificado', 'ver certificado'),),
            },
        ),
    ]
