# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-07-09 17:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('universidad', '0001_initial'),
        ('Linea_Investigacion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='linea_investigacion',
            name='Carrera',
        ),
        migrations.AddField(
            model_name='linea_investigacion',
            name='universidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='universidad.universidad'),
        ),
    ]
