# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-11-06 08:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Linea_Investigacion', '0002_auto_20180709_1249'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='linea_investigacion',
            options={'ordering': ('Nombre',)},
        ),
    ]
