# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-07-03 21:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('palabraClave', '0001_initial'),
        ('pais', '0001_initial'),
        ('Revista', '0001_initial'),
        ('baseDatos', '0001_initial'),
        ('ciudad', '0001_initial'),
        ('Linea_Investigacion', '0001_initial'),
        ('campoDetallado', '0001_initial'),
        ('Sub_Lin_Investigacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='articulos_cientificos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=500, null=True, unique=True)),
                ('estado', models.CharField(blank=True, choices=[('Receptado', 'Receptado'), ('En revisión', 'En revisión'), ('Aceptado', 'Aceptado'), ('Publicado', 'Publicado')], max_length=500, null=True)),
                ('iSSN', models.CharField(blank=True, max_length=60, null=True)),
                ('url', models.CharField(blank=True, max_length=500, null=True)),
                ('doi', models.CharField(blank=True, max_length=500, null=True)),
                ('fechaPublicacion', models.DateField(blank=True, null=True)),
                ('volumen', models.CharField(blank=True, max_length=150, null=True)),
                ('numero', models.CharField(blank=True, max_length=150, null=True)),
                ('resumen', models.TextField(blank=True, null=True)),
                ('documento', models.FileField(blank=True, null=True, upload_to='articulo/')),
                ('tipoArticulo', models.CharField(blank=True, choices=[('Científico', 'Científico'), ('De revisión', 'De revisión'), ('Ensayo', 'Ensayo'), ('Reflexión', 'Reflexión')], max_length=500, null=True)),
                ('aprobado', models.CharField(blank=True, max_length=500, null=True)),
                ('comiteEditorial', models.CharField(blank=True, max_length=500, null=True)),
                ('estPub', models.BooleanField()),
                ('desEstado', models.TextField(blank=True, null=True)),
                ('SubLinea', models.ForeignKey(blank=True, max_length=150, null=True, on_delete=django.db.models.deletion.CASCADE, to='Sub_Lin_Investigacion.sub_lin_investigacion')),
                ('baseDatos', models.ManyToManyField(blank=True, to='baseDatos.baseDatos')),
                ('ciudad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ciudad.ciudad')),
                ('detallado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='campoDetallado.campoDetallado')),
                ('lineaInves', models.ForeignKey(blank=True, max_length=150, null=True, on_delete=django.db.models.deletion.CASCADE, to='Linea_Investigacion.linea_investigacion')),
                ('pais', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pais.pais')),
                ('palabraClave', models.ManyToManyField(blank=True, to='palabraClave.palabraClave')),
                ('revista', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Revista.revista')),
            ],
            options={
                'permissions': (('ver_articulo', 'ver articulo'),),
            },
        ),
    ]
