# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-07-04 21:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Articulos_Cientificos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulos_cientificos',
            name='idioma',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
