# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-07-09 09:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campoAmplio', '0001_initial'),
        ('campoEspecifico', '0001_initial'),
        ('universidad', '0001_initial'),
        ('Articulos_Cientificos', '0003_articulos_cientificos_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulos_cientificos',
            name='amplio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='campoAmplio.campoAmplio'),
        ),
        migrations.AddField(
            model_name='articulos_cientificos',
            name='especifico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='campoEspecifico.campoEspecifico'),
        ),
        migrations.AddField(
            model_name='articulos_cientificos',
            name='university',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='universidad.universidad'),
        ),
    ]
