# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-09-09 04:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Articulos_Cientificos', '0004_auto_20180709_0408'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulos_cientificos',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, default=1),
            preserve_default=False,
        ),
    ]
