# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-09-09 04:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Articulos_Cientificos', '0005_articulos_cientificos_uploaded_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articulos_cientificos',
            name='uploaded_at',
        ),
    ]
