# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-09-09 05:09
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Articulos_Cientificos', '0010_auto_20180908_2358'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulos_cientificos',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2018, 9, 9, 5, 9, 9, 305084, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
