# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-09-09 05:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Articulos_Cientificos', '0012_auto_20180909_0014'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articulos_cientificos',
            name='AMresumen',
        ),
        migrations.RemoveField(
            model_name='articulos_cientificos',
            name='AMtitulo',
        ),
    ]
