# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-02-11 22:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Articulos_Cientificos', '0020_auto_20190211_1725'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articulos_cientificos',
            name='filialUtc',
        ),
    ]
