# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-02-12 01:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Articulos_Cientificos', '0022_articulos_cientificos_filialutc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articulos_cientificos',
            name='filialUtc',
        ),
    ]
