# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-02-18 09:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TextMining', '0001_initial'),
        ('Articulos_Cientificos', '0024_articulos_cientificos_filialutc'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulos_cientificos',
            name='statusText',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='articulos_cientificos',
            name='textMining',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='TextMining.textmining'),
        ),
    ]
